### ISSUE TITLE
Add Lucas as collaborator

### ISSUE THREAD

**Issue by sylvioalves** [zephyrproject-rtos/hal_espressif#134]
Please, add @LucasTambor as collaborator so that he can review and approve PRs. Thanks.

**Comment by stephanosio** [comment]
Done

For the record, @LucasTambor is listed in the MAINTAINERS file:
https://github.com/zephyrproject-rtos/zephyr/blob/6c888b2db187b7c15eca2a279712f54be2b342fb/MAINTAINERS.yml#L2192
