### ISSUE TITLE
Delete and rename branches

### ISSUE THREAD

**Issue by sylvioalves** [zephyrproject-rtos/hal_espressif#135]
@stephanosio Please, can you perform the following changes in this repository:

1) delete branch `hal_v4.3` -> it isn't being used at all.  
2) delete branch `hal_v4.4.1_latest` -> I accidentally push this. It can be deleted.  
3) rename default `zephyr` -> `hal_v4.3` -> Current `zephyr` was based in esp-idf v4.3. As it was updated to `v4.4.1`, this can be renamed to `hal_v4.3`.  
4) rename `hal_v4.4.1` to `zephyr` and make it default. This is the default branch set in this PR: https://github.com/zephyrproject-rtos/zephyr/pull/49682  

At the end, we only need 3 branches in here:  
`hal_v4.2` -> The initial branch used.
`hal_v4.3` -> Previous after the PR mentioned above.
`zephyr` -> latest based on v4.4.1.

**Comment by stephanosio** [comment]
Done
