### ISSUE TITLE
Incorrect display of new lines with west espressif monitor

### ISSUE THREAD

**Issue by mkettn** [zephyrproject-rtos/hal_espressif#162]
## Environment

- Development Kit:  none
- Module or chip used:  ESP32-WROOM-32
- IDF version (run ``git describe --tags`` to find it): 8c7ee781ea4c4a010740f5231709ce7b21ad96d6
- Build System:  zephyr sdk
- Operating System:     Linux
- Using an IDE?: No
- Power Supply:         USB

## Problem Description

the line endings aren't displayed correctly using IDFs serial monitor using `$ west espressif monitor`

### Expected Behavior

output as if I am using a normal console window.

### Actual Behavior

newline not always introduces a line break. sometimes the cursor position just goes to the first character position of the last line. This is a display glitch on the host side! It is due to the missing --eol argument when starting the idf monitor from west and a [bogus default value for the idf monitor.](https://github.com/espressif/esp-idf/blob/6d9d237/tools/idf_monitor.py#L79)

### Steps to reproduce

1. flash any example project with text output or shell access from zephyr.
2. connect serial console using west espressif monitor
3. output is mangled since west espressif monitor does not interpret newline correct.

### Solution
with this patch:
```diff
diff --git a/west/tools.py b/west/tools.py
index c649a7bdf..61d691049 100644
--- a/west/tools.py
+++ b/west/tools.py
@@ -136,6 +136,7 @@ class Tools(WestCommand):
         group.add_argument('-b', '--baud', default="115200", help='Serial port baud rate')
         group.add_argument('-p', '--port', help='Serial port address')
         group.add_argument('-e', '--elf', help='ELF file')
+        group.add_argument('-n', '--eol', default='CR', help='EOL to use')
 
         return parser
 
@@ -173,7 +174,7 @@ class Tools(WestCommand):
         cmd_path = Path(os.getenv("ZEPHYR_BASE")).absolute()
         if platform.system() == 'Windows':
             cmd_exec(("python.exe", monitor_path, "-p", esp_port,
-                     "-b", args.baud, elf_path), cwd=cmd_path)
+                     "-b", args.baud, elf_path, "--eol", args.eol), cwd=cmd_path)
         else:
             cmd_exec((sys.executable, monitor_path, "-p", esp_port, "-b", args.baud,
-                      elf_path), cwd=cmd_path)
+                      elf_path, "--eol", args.eol), cwd=cmd_path)

```
... it will just conduit the eol parameter from `west espressif monitor` to [espressifs serial monitor](https://github.com/espressif/esp-idf/blob/6d9d23702f366c55ca8b52c447803c19c7c62997/tools/idf_monitor_base/argument_parser.py#L55). Now you can select if you want broken new lines (CR, upstream default behaviour), or working new lines (LF). with to command: `west espressif monitor -n LF`

**Comment by sylvioalves** [comment]
@mkettn, thanks. PTAL https://github.com/zephyrproject-rtos/hal_espressif/pull/163.
