### ISSUE TITLE
GPIO 20 is not supported but actually used by some chips

### ISSUE THREAD

**Issue by Flauer741** [zephyrproject-rtos/hal_espressif#178]
## Environment

- Development Kit: Adafruit ESP32 Feather V2
- Module or chip used: ESP32-PICO-V3-02 (revision 3)
- IDF version: don't know
- Build System: west 0.14.0, Zephyr SDK 0.15.2
- Compiler version: xtensa-espressif_esp32_zephyr-elf-gcc (Zephyr SDK 0.15.2) 12.1.0
- Operating System: Linux
- Using an IDE?: Yes, VS Code
- Power Supply: USB

## Problem Description

The Adafruit board uses GPIO 20 for SCL (I2C), but this pin does not exist in the pinctl and thus cannot be configured in the device tree.

### Expected Behavior

GPIO 20 can be configured as SCL for I2C0 and the bus is then functional. This does work using the Arduino libraries & sample code provided by Espressif / Adafruit and also using the fix/workaround shown below.

### Actual Behavior

Compiler error, `I2C0_SCL_GPIO20` is undefined.

### Steps to reproduce / Code to reproduce this issue

Compile any zephyr demo (e.g. hello_world or the wifi test), but add the following device tree overlay:

```devicetree
&i2c0_default {
    group1 {
        pinmux = <I2C0_SDA_GPIO22>, <I2C0_SCL_GPIO20>;
        bias-pull-up;
        drive-open-drain;
        output-high;
    };
};

&i2c0 {
    sda-gpios = <&gpio0 22 GPIO_OPEN_DRAIN>;
    scl-gpios = <&gpio0 20 GPIO_OPEN_DRAIN>;
};
```

## Possible Fix / Workaround

Applying the following fix to zephyr/esp_shared/pincfgs/esp32.yml fixes the issue:

```diff
-    gpio: [[0, 19], [21, 23], [25, 27], [32, 33]]
+    gpio: [[0, 23], [25, 27], [32, 33]]
```

**Comment by sylvioalves** [comment]
@Flauer741, thanks for point this.
