### ISSUE TITLE
mesh_provisioner sample gets stuck after the first "Waiting for unprovisioned beacon..." message

### ISSUE THREAD

**Issue by jorcis** [zephyrproject-rtos/hal_espressif#227]
## Environment

- Development Kit:      [ESP32-DevKitC | ESP32-C3-DevKitM]
- Kit version (for WroverKit/PicoKit/DevKitC): [v1]
- Module or chip used:  [ESP32-WROOM-32 | ESP32-C3]
- IDF version: commit hash: 9531c1c17873aa4935f85864ebafd20c02062a8f
- Build System:         [Zephyr west]
- Compiler version: 
       xtensa-espressif_esp32_zephyr-elf-gcc (Zephyr SDK 0.15.2) 12.1.0
       riscv64-zephyr-elf-gcc (Zephyr SDK 0.15.2) 12.1.0
- Operating System:     [Linux]
- Using an IDE?: [No]
- Power Supply:         [USB]

## Problem Description

I'm trying mesh and mesh_provisioner samples with the latest Zephyr RTOS 3.4 version, both esp32 board and esp32c3_devkitm board. "mesh" sample works fine but "mesh_provisioner" gets stuck just after the first "Waiting for unprovisioned beacon..." message. Can anyone help? I am not sure if this could be an issue or just a config setting question!

### Expected Behavior

00> *** Booting Zephyr OS build zephyr-v3.4.0-1-g719dc245ef4f ***
00> Initializing...
00> Bluetooth initialized
00> Mesh initialized
00> Loading stored settings
00> Using stored CDB
00> Using stored settings
00> Waiting for unprovisioned beacon...
00> Waiting for unprovisioned beacon...
00> Device 63e634dd9332e8b60000000000000000 detected, press button 1 to provision.
00> Provisioning 63e634dd9332e8b60000000000000000
00> Waiting for node to be added...
00> Added node 0x0002
00> Configuring node 0x0002...
00> Element @ 0x0002: 4 + 0 models
00> Binding AppKey to model 0x002:0002
00> Binding AppKey to model 0x002:1000
00> Binding AppKey to model 0x002:1001
00> Configuration complete
00> Waiting for unprovisioned beacon...

### Actual Behavior

*** Booting Zephyr OS build zephyr-v3.4.0-1-g719dc245ef4f ***
Initializing...
Bluetooth initialized
Mesh initialized
Loading stored settings
Using stored CDB
Using stored settings
Waiting for unprovisioned beacon...

_No more messages after here (program stucks here) _

### Steps to reproduce

1. Get and install Zephyr  [](https://docs.zephyrproject.org/latest/develop/getting_started/index.html)
2. west blobs fetch hal_espressif
3. cd zephyr/samples/bluetooth/mesh_provisioner
4. west build -b esp32c3_devkitm
5. west flash && west espressif monitor

### Code to reproduce this issue

[](https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/bluetooth/mesh_provisioner)

## Debug Logs

*** Booting Zephyr OS build zephyr-v3.4.0-1-g719dc245ef4f ***
Initializing...
Bluetooth initialized
Mesh initialized
Loading stored settings
Using stored CDB
Using stored settings
Waiting for unprovisioned beacon...

_No more messages after here (program stucks here) _

**Comment by rftafas** [comment]
Could you please open this into Zephyr RTOS repo? BTW, BT Mesh is not yet supported.
