### ISSUE TITLE
Missing `mcuboot_assert_handler` function

### ISSUE THREAD

**Issue by horakdavid** [zephyrproject-rtos/hal_espressif#239]
## Problem Description

`mcuboot_assert_handler` function is missing even though `MCUBOOT_HAVE_ASSERT_H` in `mcuboot_config.h` is defined to `1`.

### Expected Behavior
Bootloader should compile when using `assert()` function
### Actual Behavior
Bootloader wouldn't compile due to missing `mcuboot_assert_handler` function

### Steps to reproduce

Build MCUBoot with `BOOT_SWAP_USING_MOVE` option enabled.

## Solution
Solution is to add `mcuboot_assert_handler` function to `zephyr/esp_shared/src/boot/esp_loader.c` or some better location.

```
void mcuboot_assert_handler(const char *file, int line, const char *func)
{
    ets_printf("assertion failed: file \"%s\", line %d, func: %s\n", file, line, func);
    abort();
}
```

**Comment by marekmatej** [comment]
Hi @horakdavid thank you for your finding. It will be addressed in new hal_espressif release.

**Comment by EricNRS** [comment]
> Hi @horakdavid thank you for your finding. It will be addressed in new hal_espressif release.

Any updates on the timing of the new hal_epressif release or are there still too many unknowns to work though?
